using System;

namespace GodotSharpPlus.Attributes;

/// <summary>
/// Specifies the accessibility level of the constructor generated by
/// <see cref="SingletonNodeAttribute"/>.
/// </summary>
[PublicAPI]
public enum SingletonNodeConstructorAccessibility : u8
{
    Public,
    Protected,
    Private,
}

/// <summary>
/// Indicates that the decorated class (a <see cref="Node"/>) can have only one
/// instance at a time.
/// </summary>
/// <param name="constructorAccessibility">
/// The accessibility level of the generated constructor.
/// </param>
/// <remarks>
/// As this attribute generates a constructor, any code that typically goes into the
/// constructor must be put in an implementation of partial method <c>Init</c>.
/// </remarks>
[PublicAPI, AttributeUsage(AttributeTargets.Class)]
public sealed class SingletonNodeAttribute(SingletonNodeConstructorAccessibility constructorAccessibility = SingletonNodeConstructorAccessibility.Public) : Attribute
{
    public readonly SingletonNodeConstructorAccessibility ConstructorAccessibility = constructorAccessibility;
}
