using System.Text;

namespace GodotSharpPlus.SourceGen.Core;

internal static class Constants
{
    public const string GodotNamespace = "Godot";
    public const string AttributeNamespace = "GodotSharpPlus.Attributes";
    public const string NodeName = "Node";
    public const string NodeQualifiedName = $"{GodotNamespace}.{NodeName}";
    public const string SourceFileNameSuffix = ".g.cs";
    public const string SourceCodeHeader = """
                                           // <auto-generated/>

                                           #nullable enable
                                           """;

    public static readonly Encoding SourceFileEncoding = Encoding.UTF8;
}
